# cloudbuild.yaml
steps:
  # build & push the container image
- name: "gcr.io/virtualjulius-bot/myfirstbot:latest"
  args: ["--cache=true", "--cache-ttl=48h", "--destination=gcr.io/virtualjulius-bot/myfirstbot:latest"]
  # Deploy container image to Cloud Run
- name: "gcr.io/virtualjulius-bot/myfirstbot"
  args: ['beta', 'run', 'deploy', 'myfirstbot', '--image', 'gcr.io/virtualjulius-bot/myfirstbot:latest', '--region', 'us-central1', '--allow-unauthenticated', '--platform', 'managed']